SELECT * FROM PCN_VW_INTEGRA_COLPLAN_FAT
--SELECT * FROM PCN_VW_INTEGRA_COLPLAN_FAT where order_code = 6853491
--SELECT * FROM PCN_VW_INTEGRA_COLPLAN_FAT where CHANNEL_CODE_LEVEL_1 = 'ME'
--SELECT * FROM PCN_VW_INTEGRA_COLPLAN_FAT where CHANNEL_CODE_LEVEL_1 = 'ME' AND ORDER_CODE = 9010833